# Generated by Django 5.2.2 on 2026-06-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
