# Generated by Django 5.2.2 on 2026-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apikeys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
