# Generated by Django 5.2.2 on 2026-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="template_name",
        ),
        migrations.AlterField(
            model_name="pagerichtext",
            name="text",
            field=models.TextField(blank=True, verbose_name="text (HTML)"),
        ),
    ]
